server:
  port: 8081

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/dlyk?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1 # ??????
      connection-timeout: 60000 #?????????,??30?
      idle-timeout: 500000 #?????????????600000?10???
      max-lifetime: 540000 #??????????????????0???????????1800000?30??
      maximum-pool-size: 12 #????????????10
      minimum-idle: 10 #????????
      pool-name: SPHHikariPool # ?????
  jackson:
    time-zone: GMT+8

  data:
    redis:
      host: 127.0.0.1
      port: 6380
      database: 0
#?????????sql???????
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true
